dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mlton-compiler
    - nasm
before_install:
  - date
  # Show environment
  - lsb_release -a
  - ulimit -a
  - cat /proc/cpuinfo
  - cat /proc/meminfo
  - g++ --version
  # Install menhir
  - cd ${HOME}
  - mkdir deb
  - cd deb
  - wget https://launchpad.net/ubuntu/+source/menhir/20160808+dfsg-1/+build/10623429/+files/libmenhir-ocaml-dev_20160808+dfsg-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/menhir/20160808+dfsg-1/+build/10623429/+files/menhir_20160808+dfsg-1_amd64.deb
  - sudo dpkg -i *.deb
  # Download flrc
  - cd ${HOME}
  - git clone https://github.com/IntelLabs/flrc.git
script:
  # Build flrc-lib
  - cd ${TRAVIS_BUILD_DIR}
  - sh bootstrap.sh
  - ./configure
  - make |& grep '^g++'
  - sudo make install
  # Building flrc
  - cd ${HOME}/flrc
  - sh bootstrap.sh
  - ./configure
  - make
  - sudo make install
after_script:
  - date
